build:
  maxIssues: 0

complexity:
  active: true
  LongMethod:
    threshold: 60
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 10
    thresholdInObjects: 15
    thresholdInEnums: 10

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

naming:
  active: true
  FunctionNaming:
    # Composable functions must start with uppercase by convention
    ignoreAnnotated:
      - 'Composable'

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 130
  ReturnCount:
    max: 3
